codecov:
  notify:
    require_ci_to_pass: yes
  ignore:
  - "build/**/*"
  - "tasks.py"
  - "setup.py"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: null
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: success
    patch:
      default:
        enabled: yes
        threshold: 30
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no