
sudo: required
dist: xenial

language: python

stages:
- name: test
  if: repo = ESSS/hookman AND tag IS NOT present
- name: deploy
  if: repo = ESSS/hookman AND tag IS present

jobs:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37

    - stage: deploy
      python: '3.6'
      env:
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: "__token__"
        password:
          secure: aplC5LMgM31ptr+HDw6o2owfIo+H+wt8ZrIs5kNOWHrVyoDQttwFAfJmvFc4SOq90UXwWQoC8lZQ6U3czON0bNYI05N7zkF8tMosz2W1riUJnbqQ2UEYrei5RJeogJ26DbPgVXU8P1OCPw0YGbof1lxL7H7vIa7eWG3VY/9IYndHwVOMvI/Ov7Pc0jGs/Sfl74WhC4kvvNPaskkD8/kGsaKSv1rHTrdMBXw/pYYQoeYH5/+tyPX63Au6yTBqpO4uBsLZJxnIpX6YkqJ6vEznAAmDu/a94wBrr0ptXTcL96ayiKlTO7MDCkPLWn/XUEI6lDMUlySoh6fSOI6k6o2huASEsRmJWi7Ffjkul2CYpPo1kMM4wJXUO17xipg0fLSygjgS+gmBdPWECCmLSSLoIEK63qSl0ZRHzVKHWlGjzo/a0othcMPf23ZesOfdQtzx/BkY7N/bjTBJoE/IeBbsuHGuzt4vpvV9ETdMprstzcsCN2v+9+jCW35548WW9A4U0P2RybELzR+e/W3bWnHz/qimoqHAUk+p0CkxkJf9PQtOr+Tfyyf75ucF7M/fVk772D/po85C/clbD0d66y88N0I8nvDaa1OAEHJyFTeLFlmw9pBEtB5DVp/fpIBu8Dd7wJOfykSUGddvbp5Sopg5swzUhpCvYo4cuba9ZTOi8ls=
        on:
          tags: true
          repo: ESSS/hookman

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-6.0
    packages:
      - clang-6.0
      - ninja-build

install:
  - pip install -U pip
  - pip install -U tox-travis tox-conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH


script: tox

branches:
  only:
    - master
    #    Use a regex for the tags in branches.only:
    #    Source: https://github.com/travis-ci/travis-ci/issues/3897
    #    The regex below catches expression that begins with "v" and groups of digits with dots
    #        Ex. v1.0.0; V1.5.3; V2.0
    #
    #    Noticed the slash character at the beginning and the end, this is required from Travis
    - /v(\d+\.)*\d/
