
sudo: required

language: python
python:
  - 3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ninja-build

install:
  - pip install -U pip tox-travis codecov codacy-coverage
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PYBIND_PATH="$HOME/miniconda/share/cmake/pybind11"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda info -a  # for debug reasons
  - conda install pybind11
  - ls $HOME/miniconda/share


script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: esss
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: esss/hookman
    python: 3.6

branches:
  only:
    - "master"
