name: hookman

dependencies:
    - python=3
    - strictyaml
    - invoke>=1.0.0
    - click>=7.0.0
    - pytest
    - pytest-cov
    - pytest-datadir
    - pytest-mock
    - pytest-regressions

    # C++ compilation
    - pybind11
    - ninja
    - cmake >=3.5.2

    {% if os.sys.platform != 'win32' %}
    - conda-forge::gcc_linux-64==7.3.0
    - conda-forge::gcc_impl_linux-64==7.3.0
    - conda-forge::gxx_linux-64==7.3.0
    - conda-forge::gxx_impl_linux-64==7.3.0
    - libgcc-ng==7.3.0
    - libstdcxx-ng==7.3.0
    - binutils_linux-64==2.31.1
    - binutils_impl_linux-64==2.31.1
    {% endif %}

    {% if os.sys.platform == 'win32' %}
    - vs2015_runtime
    {% endif %}



environment:
  PYTHONPATH:
    - {{ root }}
    - {{ root }}/build/artifacts
  LD_LIBRARY_PATH:
    - {{ root }}/build/artifacts
  PATH:
    - {{ root }}/build/artifacts
