name: hookman

dependencies:
    - python=3
    - strictyaml
    - invoke>=1.0.0
    - click>=7.0.0
    - pytest
    - pytest-cov
    - pytest-datadir
    - pytest-mock
    - pytest-regressions
    - pre-commit >=1.18.3
    - black >=19.3b0

    # C++ compilation
    - pybind11
    - ninja
    - cmake >=3.5.2

    - clangdev>=6.0.0  # [linux]
    - vs2015_runtime  # [win]



environment:
  PYTHONPATH:
    - {{ root }}
    - {{ root }}/build/artifacts
  LD_LIBRARY_PATH:
    - {{ root }}/build/artifacts
  PATH:
    - {{ root }}/build/artifacts
