name: hookman


dependencies:
    - python==3.6.5
    - strictyaml
    - invoke==1.0.0
    - click
    - pytest
    - pytest-cov
    - pytest-datadir
    - pytest-mock

    # C++ compilation
    - pybind11
    - ninja=1.7.1
    - cmake

    {% if os.sys.platform != 'win32' %}
    - clangdev==6.0.0
    {% endif %}

    {% if os.sys.platform == 'win32' %}
    - vs2015_runtime
    {% endif %}



environment:
  PYTHONPATH:
    - {{ os.path.join(root) }}
    - {{ root }}/build/artifacts
  LD_LIBRARY_PATH:
    - {{ root }}/build/artifacts
  PATH:
    - {{ root }}/build/artifacts
