/* File automatically generated by hookman, **DO NOT MODIFY MANUALLY** */
#ifndef ACME_HOOK_SPECS_HEADER_FILE
#define ACME_HOOK_SPECS_HEADER_FILE
#ifdef __cplusplus
    #define _HOOKMAN_EXTERN_C extern "C"
#else
    #define _HOOKMAN_EXTERN_C
#endif

#ifdef WIN32
    #define HOOKMAN_API_EXP _HOOKMAN_EXTERN_C __declspec(dllexport)
    #define HOOKMAN_FUNC_EXP __cdecl
#else
    #define HOOKMAN_API_EXP _HOOKMAN_EXTERN_C
    #define HOOKMAN_FUNC_EXP
#endif

HOOKMAN_API_EXP const char* HOOKMAN_FUNC_EXP acme_version_api() {
    return "v1";
}

HOOKMAN_API_EXP const char* HOOKMAN_FUNC_EXP get_plugin_id() {
    return "acme";
}


/*!
Docs for Friction Factor
    Input:
        Testing indentation
    Return:
            Integer
*/
#define HOOK_FRICTION_FACTOR(v1, v2) HOOKMAN_API_EXP int HOOKMAN_FUNC_EXP acme_v1_friction_factor(int v1, double v2[2])


#endif // ACME_HOOK_SPECS_HEADER_FILE
