import ctypes
import os
import sys
from collections.abc import Iterator
from collections.abc import Sequence
from contextlib import contextmanager
from pathlib import Path

from hookman.exceptions import SharedLibraryLoadError


def find_config_files(
    plugin_dirs: Sequence[Path] | Path, *, ignored_sub_dir_names: Sequence[str] = ()
) -> Sequence[Path]:
    """
    Try to find all configurations files from plugins implementations on the given path (plugins_dirs)
    If in the given there is any plugin, this function will return None
    """
    config_files: list[Path] = []

    if not isinstance(plugin_dirs, Sequence):
        plugin_dirs = [plugin_dirs]

    def is_ignored(filename: Path, ignored_dirs: Sequence[Path]) -> bool:
        return any(folder in filename.parents for folder in ignored_dirs)

    for plugin_dir in plugin_dirs:
        ignored_dirs = [plugin_dir / name for name in ignored_sub_dir_names]
        config_files += (
            filename
            for filename in plugin_dir.glob("**/plugin.yaml")
            if not is_ignored(filename, ignored_dirs)
        )

    return config_files


@contextmanager
def change_path_env(shared_lib_path: str) -> Iterator[None]:
    """
    Change PATH environment adding the shared library path to it.
    """
    old_path = os.environ["PATH"]
    handle = None
    if sys.platform.startswith("win"):
        # We explict opted to not cover this on windows.
        os.environ["PATH"] = old_path + os.pathsep + os.path.dirname(shared_lib_path)
        handle = os.add_dll_directory(os.path.dirname(shared_lib_path))  # pragma: no cover
    try:
        yield
    finally:
        os.environ["PATH"] = old_path
        if handle is not None:
            handle.close()  # pragma: no cover


@contextmanager
def suppress_dll_error_dialog() -> Iterator[None]:  # pragma: no cover
    """
    Suppress the Windows hard-error dialog that the OS loader shows when a
    DLL fails to resolve its imports or entry points.

    No-op on non-Windows platforms.

    The same suppression logic is duplicated in the C++ `load_dll` function
    generated by `hookman_generator.py` — keep both in sync when changing
    the error-mode flags or the error-handling strategy.
    """
    if sys.platform != "win32":
        yield
        return

    # Without this, `LoadLibraryW` raises a modal dialog for certain load
    # failures (missing procedure, missing module) that blocks the process until
    # manually dismissed. Setting `SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX`
    # via `SetThreadErrorMode` makes the loader return NULL to the caller instead,
    # so the error is handled programmatically via the normal `OSError`/`GetLastError`
    # path.
    SEM_FAILCRITICALERRORS = 0x0001
    SEM_NOOPENFILEERRORBOX = 0x8000
    # ctypes.WinDLL is Windows-only; mypy on non-Windows platforms does not resolve this attribute.
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)  # type: ignore[attr-defined]
    old_mode = ctypes.c_uint(0)
    # The thread-local `SetThreadErrorMode` is used rather than the process-wide
    # `SetErrorMode` to avoid interfering with other threads.
    if not kernel32.SetThreadErrorMode(
        SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX,
        ctypes.byref(old_mode),
    ):
        raise OSError(ctypes.get_last_error(), "SetThreadErrorMode failed")
    try:
        yield
    finally:
        if not kernel32.SetThreadErrorMode(old_mode.value, None):
            raise OSError(ctypes.get_last_error(), "SetThreadErrorMode restore failed")


@contextmanager
def load_shared_lib(shared_lib_path: str) -> Iterator[ctypes.CDLL]:
    """
    Load a shared library using ctypes freeing the resource at end.

    On Windows, the OS hard-error dialog for unresolved DLL imports is
    suppressed so that load failures surface as `SharedLibraryLoadError`
    instead of blocking modal dialogs.

    :raises SharedLibraryLoadError:
        If the shared library exists but fails to load, e.g. because of an
        incompatible or missing dependency DLL.
    """
    with change_path_env(shared_lib_path):
        with suppress_dll_error_dialog():
            try:
                plugin_dll = ctypes.cdll.LoadLibrary(shared_lib_path)
            except OSError as error:
                raise SharedLibraryLoadError(Path(shared_lib_path), str(error)) from error

    try:
        yield plugin_dll
    finally:
        if sys.platform == "win32":
            from _ctypes import FreeLibrary

            FreeLibrary(plugin_dll._handle)
        else:
            from _ctypes import dlclose

            dlclose(plugin_dll._handle)
